# Permalinks
permalink:           pretty

# Setup
title:               C. Bonda
tagline:             An Extremely Average Data Science Blog
url:                 http://charan-bonda.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Charan Bonda
  url:               
  email:             charan.bonda@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/charanbonda123

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
